name: CI

on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    # Weekly run (UTC) to include heavy/ignored integration tests
    - cron: "0 3 * * 0"
  workflow_dispatch:
    inputs:
      run_heavy_tests:
        description: "Run ignored heavy integration tests"
        type: boolean
        default: false
      rust_toolchain:
        description: "Rust toolchain to use (stable | beta | nightly | <version>)"
        required: false
        default: "stable"

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0

jobs:
  check-and-tests:
    name: Check, Lint, Build, Unit + Integration (non-ignored)
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ inputs.rust_toolchain || 'stable' }}
          components: rustfmt, clippy

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: rustfmt (check)
        run: cargo fmt --all -- --check

      - name: clippy (warn-only)
        run: cargo clippy --all-targets -- -W warnings

      - name: Post lint summary
        if: always()
        run: |
          {
            echo "### Linting"
            echo
            echo "- Clippy ran in warn-only mode (-W warnings)."
            echo "- Warnings are logged but do not fail the pipeline."
            echo
            echo "Consider re-enabling -D warnings once the codebase is clean."
          } >> "$GITHUB_STEP_SUMMARY"

      - name: Build (all targets)
        run: cargo build --all --locked

      - name: Unit and integration tests (non-ignored)
        run: cargo test --workspace --all-features -- --nocapture

      - name: Explicit CLI integration tests (non-ignored)
        run: cargo test --test cli_integration -- --nocapture

  heavy-integration:
    name: Integration (ignored/heavy)
    runs-on: ubuntu-latest
    timeout-minutes: 60
    needs: check-and-tests
    if: ${{ github.event_name == 'schedule' || inputs.run_heavy_tests }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ inputs.rust_toolchain || 'stable' }}

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2

      - name: Run ignored/heavy CLI integration tests
        run: cargo test --test cli_integration -- --ignored --nocapture

      - name: Post summary
        if: always()
        run: |
          {
            echo "### Heavy Integration Tests"
            echo
            echo "- Trigger: ${{ github.event_name }}"
            echo "- Toolchain: ${{ inputs.rust_toolchain || 'stable' }}"
            echo
            echo "This job executes tests marked with #[ignore] (heavier/longer)."
          } >> "$GITHUB_STEP_SUMMARY"
