name: Docs

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: docs-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  CARGO_INCREMENTAL: 0

jobs:
  build:
    name: Build Rust API Docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Set up Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache Cargo
        uses: Swatinem/rust-cache@v2
        with:
          workspaces: |
            ds-r1_rs

      - name: Build cargo docs
        env:
          RUSTDOCFLAGS: -D warnings
        run: |
          cargo doc --no-deps --all-features
          # Create a top-level index to redirect to the crate docs
          mkdir -p target/doc
          cat > target/doc/index.html <<'EOF'
          <!doctype html>
          <html lang="en">
          <head>
            <meta charset="utf-8">
            <meta http-equiv="refresh" content="0; url=ds_r1_rs/index.html">
            <title>DeepSeek R1 (Rust) Docs</title>
          </head>
          <body>
            <p>Redirecting to <a href="ds_r1_rs/index.html">ds_r1_rs/index.html</a>…</p>
          </body>
          </html>
          EOF

      - name: Upload artifact to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: target/doc

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
